name: energy-data-platform
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=17
  - pyspark>=3.5,<4.0
  - pyyaml>=6.0,<7.0
  - pyodbc>=5.0,<6.0
  - fastapi>=0.110,<1.0
  - uvicorn>=0.29,<1.0
  - python-dotenv>=1.0,<2.0
  - pytest>=8.0,<9.0
  - pip
  - pip:
      - azure-eventhub>=5.12,<6.0
